#!/bin/sh
echo "Running unit tests before commit..."
if ! make test; then
  echo "Tests failed. Commit aborted."
  exit 1
fi

echo "Running behave tests before commit..."
if ! make test_bb; then
  echo "Tests failed. Commit aborted."
  exit 1
fi


